### ISSUE TITLE
Migrate bee chart to environment configuration like docker compose env

### ISSUE THREAD

**Issue by mfw78** [ethersphere/helm#83]
**Problem**
Using a singular `ConfigMap` hamstrings flexibility when deploying at scale where environment variables may be worthy substitutions to allow for overriding on a per-pod basis. Given that docker compose is already using env files, the ethersphere/bee and ethersphere/clef are suitable candidates for sole configuration via environment variables.

**Fix Requested**

- [ ] Remove ConfigMap file template
- [ ] Migrate beeConfig to an environment variable / value construct for inclusion in the statefulset

**Comment by vandot** [comment]
Hi @mfw78 thanks you for the issue. Can you please elaborate how would you manage that override deploying at scale?
This could be done, but it would need careful consideration.

**Comment by mfw78** [comment]
I did implement this for my deployment. When taking into account https://docs.ethswarm.org/docs/installation/configuration/#precedence-order-of-configuration, it is possible to handle the configuration without a `ConfigMap`. The specific problem that the `ConfigMap` causes is that the `bee.yaml` file is essentially replicated, and as changes occur upstream, these will cause repetitive issues down stream.

The way I handled it was by retaining `.Values.beeConfig`, however I pretty much commented out all of the configuration, so as to ensure that the installed `bee` pods follow the upstream default configuration as closely as possible. My swarm's values.yaml is as follows:

```yaml
beeConfig:
  ## Enable clef signer
  clef_signer_enable: true
  ## Set clef signer endpoint
  clef_signer_endpoint: "http://127.0.0.1:8550"
  ## Enable debug HTTP API
  debug_api_enable: true
  ## Password for decrypting keys (please change it for production deployments)
  ## If not set, it will be automatically generated
  password: "<censored>"
  ## Set swap ethereum blockchain endpoint
  swap_endpoint: "http://<censored>:8545"
```

I adjusted the chart's values.yaml for beeConfig as follows:
```yaml
beeConfig:
  api_addr: :1633
  debug_api_addr: :1635
  p2p_addr: :1634
  password: beekeeper
```

The only reason why I maintained the ports was so that the ports may be consumed by their appropriate `Service` definitions. Then to handle the configuration of bee via environmental variables, I declared the following in `bee` container's `StatefulSet`:

```yaml
          env:
            {{- range $key, $value := $.Values.beeConfig }}
            - name: BEE_{{ $key | upper }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
```

Using this method would allow for `beeConfig` to specify cluster-wide configuration options, freeing the need of delicate handling of `bee.yaml`, specifically dropping the need for copying / editing as per the `init-natport` container. `initContainers` would now be free to just simply write to `bee.yaml` the specific configuration overrides, in accordance with the precedence of configuration order, as well as removing the duplication of `bee.yaml` upstream in the Helm charts.

**Comment by vandot** [comment]
@mfw78 I thought little bit about this and figured out that it would be sufficient to create new section (`beeEnv`) inside `values.yaml` and use that for ENV variables
```yaml
beeEnv:
  ## Enable clef signer
  clef_signer_enable: true
  ## Set clef signer endpoint
  clef_signer_endpoint: "http://127.0.0.1:8550"
  ## Enable debug HTTP API
  debug_api_enable: true
  ## Password for decrypting keys (please change it for production deployments)
  ## If not set, it will be automatically generated
  password: "<censored>"
  ## Set swap ethereum blockchain endpoint
  swap_endpoint: "http://<censored>:8545"
```
And inside statefulset.yaml add something like this
```yaml
          {{- if $.Values.beeEnv }}
          env:
            {{- range $key, $value := $.Values.beeEnv }}
            - name: BEE_{{ $key | upper }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
```
This way we will keep both options and beeEnv will overwrite options set inside config.
What do you think?
